module.exports = {
	webviewStack: document.getElementById("webview-stack"),
	urlInput: document.getElementById("url-input"),
	goBtn: document.getElementById("go-btn"),
	fluxBar: document.getElementById("flux-bar"),
	menuBtn: document.getElementById("menu-btn"),
	dropdownMenu: document.getElementById("dropdown-menu"),
	settingsBtn: document.getElementById("settings-btn"),
	addBookmarkBtn: document.getElementById("add-bookmark-btn"),
	viewBookmarksBtn: document.getElementById("view-bookmarks-btn"),
	exitBtn: document.getElementById("exit-btn"),
	resolutionSubmenu: document.getElementById("resolution-submenu"),
	windowStatus: document.getElementById("window-status"),
	pageTitle: document.getElementById("page-title"),
};
