module.exports = {
	webviewStack: document.getElementById("webview-stack"),
	urlInput: document.getElementById("url-input"),
	goBtn: document.getElementById("go-btn"),
	backBtn: document.getElementById("back-btn"),
	forwardBtn: document.getElementById("forward-btn"),
	refreshBtn: document.getElementById("refresh-btn"),
	fluxBar: document.getElementById("flux-bar"),
	menuBtn: document.getElementById("menu-btn"),
	dropdownMenu: document.getElementById("dropdown-menu"),
	settingsBtn: document.getElementById("settings-btn"),
	addBookmarkBtn: document.getElementById("add-bookmark-btn"),
	viewBookmarksBtn: document.getElementById("view-bookmarks-btn"),
	exitBtn: document.getElementById("exit-btn"),
	resolutionSubmenu: document.getElementById("resolution-submenu"),
	directionIndicatorPanel: document.getElementById("direction-indicator-panel"),
	directionIndicatorDial: document.getElementById("direction-indicator-dial"),
	directionIndicatorMarkers: document.getElementById("direction-indicator-markers"),
	directionIndicatorRotateHandle: document.getElementById(
		"direction-indicator-rotate-handle",
	),
};
