name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
category-template: "### $TITLE"
no-changes-template: "- 暂无变更"
template: |
  ## 更新内容

  $CHANGES

categories:
  - title: 新功能
    when:
      labels:
        - feat
    semver-increment: minor

  - title: 功能改进
    when:
      labels:
        - improve
    semver-increment: patch

  - title: 问题修复
    when:
      labels:
        - fix
    semver-increment: patch

  - title: 重构与维护
    when:
      labels:
        - refactor
        - chore
    semver-increment: patch

  - title: 其他变更
    semver-increment: patch

  - title: 跳过更新日志
    type: pre-exclude
    when:
      labels:
        - skip-changelog

  - title: 重大变更
    type: version-resolver
    semver-increment: major
    when:
      labels:
        - major

autolabeler:
  - label: feat
    title:
      - '/^feat[:(]/i'

  - label: fix
    title:
      - '/^fix[:(]/i'

  - label: improve
    title:
      - '/^improve[:(]/i'

  - label: refactor
    title:
      - '/^refactor[:(]/i'

  - label: chore
    title:
      - '/^chore[:(]/i'

  - label: major
    title:
      - '/^\w+(?:\([^)]*\))?!:/i'
    body:
      - '/BREAKING CHANGE/i'

  - label: skip-changelog
    title:
      - '/^version[:(]/i'
