module.exports = {
	shortcutList: document.getElementById("shortcut-list"),
	saveBtn: document.getElementById("save-btn"),
	cancelBtn: document.getElementById("cancel-btn"),
	checkUpdateBtn: document.getElementById("check-update-btn"),
	downloadUpdateBtn: document.getElementById("download-update-btn"),
	updateStatus: document.getElementById("update-status"),
	installUpdateBtn: document.getElementById("install-update-btn"),
	debugModeToggle: document.getElementById("debug-mode-toggle"),
	bossKeyProtectionToggle: document.getElementById(
		"boss-key-protection-toggle",
	),
	alwaysOnTopToggle: document.getElementById("always-on-top-toggle"),
	directionIndicatorToggle: document.getElementById(
		"direction-indicator-toggle",
	),
	versionNumber: document.getElementById("version-number"),
	gitPatInput: document.getElementById("git-pat"),
	gitRemoteInput: document.getElementById("git-remote"),
	gitNameInput: document.getElementById("git-name"),
	gitEmailInput: document.getElementById("git-email"),
	languageSelectCustom: document.getElementById("language-select-custom"),
	languageSelect: document.getElementById("language-select"),
	languageSelectTrigger: document.getElementById("language-select-trigger"),
	languageSelectLabel: document.getElementById("language-select-label"),
	languageSelectMenu: document.getElementById("language-select-menu"),
	languageSelectOptions: Array.from(
		document.querySelectorAll("#language-select-menu .custom-select-option"),
	),
	videoForwardSecondsInput: document.getElementById("video-forward-seconds"),
	videoBackwardSecondsInput: document.getElementById("video-backward-seconds"),
	videoLongPressRateInput: document.getElementById("video-long-press-rate"),
	syncBookmarksBtn: document.getElementById("sync-bookmarks-btn"),
	pullBookmarksBtn: document.getElementById("pull-bookmarks-btn"),
	syncAllBtn: document.getElementById("sync-all-btn"),
	pullAllBtn: document.getElementById("pull-all-btn"),
	clearLogsToggle: document.getElementById("clear-logs-toggle"),
	clearKeyConfigToggle: document.getElementById("clear-key-config-toggle"),
	clearWindowConfigToggle: document.getElementById(
		"clear-window-config-toggle",
	),
	clearAppConfigToggle: document.getElementById("clear-app-config-toggle"),
	clearResolutionPresetsToggle: document.getElementById(
		"clear-resolution-presets-toggle",
	),
	cacheClearBtn: document.getElementById("cache-clear-btn"),
	resolutionList: document.getElementById("resolution-list"),
	presetName: document.getElementById("preset-name"),
	presetWidth: document.getElementById("preset-width"),
	presetHeight: document.getElementById("preset-height"),
	aspectRatioLock: document.getElementById("aspect-ratio-lock"),
	addPresetBtn: document.getElementById("add-preset-btn"),
};
